### ISSUE TITLE
Ported to ATTiny2313

### ISSUE THREAD

**Issue by TCWORLD** [rayshobby/hid-serial#2]
After a lot of optimising for size and writing chunks of the code in assembly and removing the class, I managed to shrink HIDSerial down to a compile size of 2046 bytes flash and 97 bytes ram including routines to use the hardware UART module on the ATTiny2313. It fits with 2 bytes to spare and works :D
I needed a USB-USART (TxD, RxD, Clk) converter for a project I am working on and this has made that possible.

**Comment by rayshobby** [comment]
Very cool. Thanks!
